-- ═══════════════════════════════════════════════════════════════════════════
--  NEMO SPORTS · CANONICAL SCHEMA  (PostgreSQL 15+)
--  Migration 0001 — canonical entities, provider mapping, SDL configuration
-- ═══════════════════════════════════════════════════════════════════════════
--
--  Design rules encoded here:
--   · every canonical entity is a UUID generated by the SDL and never reused
--     (Instruction 4 — canonical ids are sacred; rows are deactivated, not deleted)
--   · all timestamps are stored in UTC (timestamptz); local time is a display concern
--   · provider-specific values live in mapping tables or JSONB extension columns,
--     never in the canonical columns
--   · bilingual text is a first-class column pair (name_ar / name_en)
--   · audit trails are append-only and retained for at least 90 days

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()

-- ─── reference data ────────────────────────────────────────────────────────

CREATE TABLE sports (
  id              uuid PRIMARY KEY,
  slug            text        NOT NULL UNIQUE,
  name_ar         text        NOT NULL,
  name_en         text        NOT NULL,
  short_name_ar   text        NOT NULL,
  short_name_en   text        NOT NULL,
  icon            text,
  is_active       boolean     NOT NULL DEFAULT true,
  display_order   integer     NOT NULL DEFAULT 100,
  config          jsonb       NOT NULL DEFAULT '{}'::jsonb,   -- periods, scoring unit, stat vocabulary
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE countries (
  id          uuid PRIMARY KEY,
  iso2        char(2)     NOT NULL UNIQUE,
  iso3        char(3)     NOT NULL UNIQUE,
  name_ar     text        NOT NULL,
  name_en     text        NOT NULL,
  continent   text,
  flag_url    text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── competitions ──────────────────────────────────────────────────────────

CREATE TABLE competitions (
  id                uuid PRIMARY KEY,
  sport_id          uuid NOT NULL REFERENCES sports(id),
  country_id        uuid REFERENCES countries(id),
  name_ar           text NOT NULL,
  name_en           text NOT NULL,
  short_name_ar     text NOT NULL,
  short_name_en     text NOT NULL,
  slug              text NOT NULL UNIQUE,
  logo_url          text,
  type              text NOT NULL DEFAULT 'league'
                    CHECK (type IN ('league','cup','tournament','friendly','international','playoff')),
  gender            text NOT NULL DEFAULT 'male' CHECK (gender IN ('male','female','mixed')),
  age_category      text NOT NULL DEFAULT 'senior'
                    CHECK (age_category IN ('senior','u23','u21','u19','u18','youth')),
  is_active         boolean NOT NULL DEFAULT true,
  is_featured       boolean NOT NULL DEFAULT false,
  display_order     integer NOT NULL DEFAULT 100,
  current_season_id uuid,                       -- FK added after seasons exists
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_competitions_sport  ON competitions(sport_id) WHERE is_active;
CREATE INDEX idx_competitions_feat   ON competitions(display_order) WHERE is_featured AND is_active;

CREATE TABLE seasons (
  id             uuid PRIMARY KEY,
  competition_id uuid NOT NULL REFERENCES competitions(id),
  name           text NOT NULL,                 -- "2025/2026" or "2026"
  slug           text NOT NULL,
  start_date     date,
  end_date       date,
  is_current     boolean NOT NULL DEFAULT false,
  status         text NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming','active','completed')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (competition_id, slug)
);
CREATE UNIQUE INDEX idx_seasons_one_current ON seasons(competition_id) WHERE is_current;

ALTER TABLE competitions
  ADD CONSTRAINT fk_competitions_current_season
  FOREIGN KEY (current_season_id) REFERENCES seasons(id) DEFERRABLE INITIALLY DEFERRED;

-- ─── venues, teams, players ────────────────────────────────────────────────

CREATE TABLE venues (
  id           uuid PRIMARY KEY,
  name_ar      text NOT NULL,
  name_en      text NOT NULL,
  city_ar      text,
  city_en      text,
  country_id   uuid REFERENCES countries(id),
  capacity     integer CHECK (capacity IS NULL OR capacity >= 0),
  surface      text,
  lat          numeric(9,6),
  lng          numeric(9,6),
  image_url    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE teams (
  id              uuid PRIMARY KEY,
  sport_id        uuid NOT NULL REFERENCES sports(id),
  country_id      uuid REFERENCES countries(id),
  name_ar         text NOT NULL,
  name_en         text NOT NULL,
  short_name_ar   text NOT NULL,
  short_name_en   text NOT NULL,
  abbreviation    text NOT NULL,
  slug            text NOT NULL UNIQUE,
  logo_url        text,
  logo_source     text,                          -- provider or "generated"
  founded_year    smallint,
  venue_id        uuid REFERENCES venues(id),
  primary_color   char(7),
  secondary_color char(7),
  is_national     boolean NOT NULL DEFAULT false,
  type            text NOT NULL DEFAULT 'club' CHECK (type IN ('club','national','franchise')),
  is_active       boolean NOT NULL DEFAULT true,
  social          jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_teams_sport ON teams(sport_id) WHERE is_active;
CREATE INDEX idx_teams_name  ON teams USING gin (to_tsvector('simple', name_en || ' ' || name_ar));

CREATE TABLE players (
  id                  uuid PRIMARY KEY,
  sport_id            uuid NOT NULL REFERENCES sports(id),
  current_team_id     uuid REFERENCES teams(id),
  country_id          uuid REFERENCES countries(id),
  full_name_ar        text NOT NULL,
  full_name_en        text NOT NULL,
  slug                text NOT NULL UNIQUE,
  date_of_birth       date,
  position            text,
  jersey_number       smallint,
  photo_url           text,
  photo_attribution   text,                      -- licence source; NULL means "do not display"
  photo_licence_ok    boolean NOT NULL DEFAULT false,
  height_cm           smallint,
  weight_kg           smallint,
  foot_preference     text CHECK (foot_preference IN ('right','left','both')),
  career_started_year smallint,
  is_active           boolean NOT NULL DEFAULT true,
  biography_ar        text,
  biography_en        text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_players_team ON players(current_team_id) WHERE is_active;
CREATE INDEX idx_players_name ON players USING gin (to_tsvector('simple', full_name_en || ' ' || full_name_ar));

-- ─── matches ───────────────────────────────────────────────────────────────

CREATE TABLE matches (
  id               uuid PRIMARY KEY,
  sport_id         uuid NOT NULL REFERENCES sports(id),
  competition_id   uuid NOT NULL REFERENCES competitions(id),
  season_id        uuid REFERENCES seasons(id),
  round            text,
  home_team_id     uuid REFERENCES teams(id),
  away_team_id     uuid REFERENCES teams(id),
  venue_id         uuid REFERENCES venues(id),
  scheduled_at     timestamptz NOT NULL,          -- always UTC
  status           text NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled','live','halftime','extra_time','extra_time_halftime',
                                     'penalty_shootout','finished','postponed','cancelled','suspended',
                                     'abandoned','walkover','awarded')),
  home_score       smallint,
  away_score       smallint,
  periods          jsonb NOT NULL DEFAULT '[]'::jsonb,   -- [{label,home,away}]
  aggregate_home   smallint,
  aggregate_away   smallint,
  winner           text CHECK (winner IN ('home','away','draw')),
  leg              smallint,
  neutral_venue    boolean NOT NULL DEFAULT false,
  referee_name     text,
  referee_country  text,
  attendance       integer,
  is_featured      boolean NOT NULL DEFAULT false,
  extension        jsonb NOT NULL DEFAULT '{}'::jsonb,   -- sport-specific payload + provider provenance
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_score_consistency CHECK (
    (status IN ('finished','live','halftime','extra_time','extra_time_halftime','penalty_shootout','awarded','walkover'))
    OR (home_score IS NULL AND away_score IS NULL)
  )
);
CREATE INDEX idx_matches_day        ON matches(scheduled_at);
CREATE INDEX idx_matches_competition ON matches(competition_id, scheduled_at);
CREATE INDEX idx_matches_status     ON matches(status) WHERE status IN ('live','halftime','extra_time','penalty_shootout');
CREATE INDEX idx_matches_teams      ON matches(home_team_id, scheduled_at DESC);
CREATE INDEX idx_matches_away_teams ON matches(away_team_id, scheduled_at DESC);

CREATE TABLE match_events (
  id                  text PRIMARY KEY,           -- provider event id or SDL hash
  match_id            uuid NOT NULL REFERENCES matches(id),
  type                text NOT NULL,
  minute              smallint,
  additional_minute   smallint,
  team_id             uuid REFERENCES teams(id),
  player_id           uuid REFERENCES players(id),
  secondary_player_id uuid REFERENCES players(id),
  description         text,
  provider            text NOT NULL,
  provider_event_id   text,
  received_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_events_match ON match_events(match_id, minute);

CREATE TABLE match_stats (
  id          text PRIMARY KEY,
  match_id    uuid NOT NULL REFERENCES matches(id),
  team_id     uuid NOT NULL REFERENCES teams(id),
  type        text NOT NULL,
  value       text NOT NULL,
  period      text NOT NULL DEFAULT 'total',
  provider    text NOT NULL,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (match_id, team_id, type, period)
);

CREATE TABLE standings (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id  uuid NOT NULL REFERENCES competitions(id),
  season_id       uuid NOT NULL REFERENCES seasons(id),
  group_name      text,
  team_id         uuid NOT NULL REFERENCES teams(id),
  position        smallint NOT NULL,
  played          smallint NOT NULL DEFAULT 0,
  won             smallint NOT NULL DEFAULT 0,
  drawn           smallint NOT NULL DEFAULT 0,
  lost            smallint NOT NULL DEFAULT 0,
  goals_for       smallint NOT NULL DEFAULT 0,
  goals_against   smallint NOT NULL DEFAULT 0,
  goal_difference smallint GENERATED ALWAYS AS (goals_for - goals_against) STORED,
  points          smallint NOT NULL DEFAULT 0,
  form            text,                            -- "WWDLW"
  status          text CHECK (status IN ('champion','promotion','promotion_playoff','cup_position',
                                         'relegation_playoff','relegation')),
  provider        text NOT NULL,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, group_name, team_id)
);
CREATE INDEX idx_standings_season ON standings(season_id, group_name, position);

CREATE TABLE top_scorers (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competitions(id),
  season_id     uuid NOT NULL REFERENCES seasons(id),
  player_id     uuid NOT NULL REFERENCES players(id),
  team_id       uuid REFERENCES teams(id),
  goals         smallint NOT NULL DEFAULT 0,
  appearances   smallint NOT NULL DEFAULT 0,
  penalties     smallint NOT NULL DEFAULT 0,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, player_id)
);

-- ─── provider mapping (§3.4) ───────────────────────────────────────────────

CREATE TABLE provider_entity_map (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type   text NOT NULL
                CHECK (entity_type IN ('sport','competition','season','match','team','player','venue','country','standing')),
  canonical_id  uuid NOT NULL,
  provider      text NOT NULL,
  provider_id   text NOT NULL,
  confidence    numeric(4,3) NOT NULL DEFAULT 1 CHECK (confidence BETWEEN 0 AND 1),
  verified      boolean NOT NULL DEFAULT false,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_type, provider, provider_id)
);
CREATE INDEX idx_mapping_canonical ON provider_entity_map(entity_type, canonical_id);
CREATE INDEX idx_mapping_review    ON provider_entity_map(updated_at) WHERE NOT verified;

-- ─── SDL configuration (§3.5, §3.8, §3.9) ──────────────────────────────────

CREATE TABLE provider_priority (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sport         text NOT NULL DEFAULT '*',
  competition   text NOT NULL DEFAULT '*',        -- competition slug or '*'
  data_type     text NOT NULL,
  provider      text NOT NULL,
  role          text NOT NULL CHECK (role IN ('primary','secondary','fallback','disabled')),
  enabled       boolean NOT NULL DEFAULT true,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid,
  UNIQUE (sport, competition, data_type, provider)
);

CREATE TABLE provider_rate_limits (
  provider      text PRIMARY KEY,
  per_second    integer,
  per_minute    integer,
  per_hour      integer,
  per_day       integer,
  per_month     integer,
  concurrency   integer,
  throttle_at   numeric(3,2) NOT NULL DEFAULT 0.85,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE provider_health (
  provider              text PRIMARY KEY,
  status                text NOT NULL DEFAULT 'healthy'
                        CHECK (status IN ('healthy','degraded','rate_limited','down','disabled')),
  enabled               boolean NOT NULL DEFAULT true,
  last_success_at       timestamptz,
  last_failure_at       timestamptz,
  latency_avg_1h_ms     integer,
  latency_avg_24h_ms    integer,
  error_rate            numeric(5,4) NOT NULL DEFAULT 0,
  conflicts_24h         integer NOT NULL DEFAULT 0,
  freshness_score       numeric(4,3) NOT NULL DEFAULT 1,
  consecutive_failures  integer NOT NULL DEFAULT 0,
  consecutive_successes integer NOT NULL DEFAULT 0,
  failover_active       boolean NOT NULL DEFAULT false,
  failover_since        timestamptz,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE data_conflicts (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  severity       text NOT NULL CHECK (severity IN ('critical','high','medium','low')),
  field          text NOT NULL,
  entity_type    text NOT NULL,
  entity_id      text NOT NULL,
  values         jsonb NOT NULL DEFAULT '{}'::jsonb,
  providers      text[] NOT NULL DEFAULT '{}',
  detected_at    timestamptz NOT NULL DEFAULT now(),
  resolved       boolean NOT NULL DEFAULT false,
  resolved_value jsonb,
  resolution     text CHECK (resolution IN ('automatic','manual')),
  resolved_at    timestamptz,
  resolved_by    uuid,
  notes          text
);
CREATE INDEX idx_conflicts_open ON data_conflicts(severity, detected_at) WHERE NOT resolved;

CREATE TABLE conflict_rules (
  field      text PRIMARY KEY,
  severity   text NOT NULL CHECK (severity IN ('critical','high','medium','low')),
  strategy   text NOT NULL CHECK (strategy IN ('primary_provider_wins','most_recent_wins','manual_review','reject_change')),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ─── cost + audit (§3.8, §12.5) ────────────────────────────────────────────

CREATE TABLE provider_call_log (
  id           bigserial PRIMARY KEY,
  provider     text NOT NULL,
  data_type    text NOT NULL,
  request_key  text NOT NULL,
  outcome      text NOT NULL CHECK (outcome IN ('success','cached','coalesced','rate_limited','error','skipped')),
  duration_ms  integer,
  http_status  smallint,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_call_log_provider ON provider_call_log(provider, created_at DESC);
CREATE INDEX idx_call_log_day      ON provider_call_log(created_at);

-- Append-only: no UPDATE/DELETE, retained ≥ 90 days (§12.5)
CREATE TABLE audit_log (
  id          bigserial PRIMARY KEY,
  actor_id    uuid,
  actor_role  text,
  action      text NOT NULL,
  entity_type text,
  entity_id   text,
  before      jsonb,
  after       jsonb,
  ip          inet,
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_entity ON audit_log(entity_type, entity_id, created_at DESC);
CREATE INDEX idx_audit_actor  ON audit_log(actor_id, created_at DESC);

CREATE RULE audit_log_no_update AS ON UPDATE TO audit_log DO INSTEAD NOTHING;
CREATE RULE audit_log_no_delete AS ON DELETE TO audit_log DO INSTEAD NOTHING;

-- ─── updated_at trigger ────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sports','countries','competitions','seasons','venues','teams','players','matches']
  LOOP
    EXECUTE format('CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_updated_at()', t, t);
  END LOOP;
END $$;
